REM do not edit this file from visual studio
cd C:\Git\ProjectManager\ProjectManager\src\ProjectManager.API
set ASPNETCORE_ENVIRONMENT=development
dotnet bin\Debug\netcoreapp1.1\projectmanager.api.dll --server.urls "http://localhost:51513/"
