REM do not edit this file from visual studio
cd C:\Git\ProjectManager\ProjectManager\src\ProjectManager.WCF
set ASPNETCORE_ENVIRONMENT=development
"c:\Program Files (x86)\IIS Express\iisexpress" /config:C:\Git\ProjectManager\ProjectManager\.vs\config\applicationhost.config /site:ProjectManager.WCF
